# Generated by Django 3.2.12 on 2022-04-17 16:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workers',
            new_name='Worker',
        ),
        migrations.AlterModelManagers(
            name='worker',
            managers=[
                ('from_replica', django.db.models.manager.Manager()),
            ],
        ),
    ]
