# Generated by Django 3.2.12 on 2022-04-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20220417_1609'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='worker',
            table='worker',
        ),
    ]
