# Generated by Django 3.2.12 on 2022-04-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_worker_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='worker',
            managers=[
            ],
        ),
    ]
